# Generated by Django 3.2.12 on 2023-07-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('sim_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('sim_owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userregistry')),
                ('sima_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.companyregistry')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_desc', models.TextField(max_length=300)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userregistry')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('manufactured_in', models.CharField(max_length=100)),
                ('device_status', models.CharField(max_length=50)),
                ('device_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.companyregistry')),
                ('device_owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userregistry')),
            ],
        ),
    ]
