# Generated by Django 3.2.12 on 2023-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_deviceregistry_device_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistry',
            name='device_sim_name',
            field=models.CharField(default='No sim', max_length=100),
        ),
    ]
